// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0
import type { VariableDto, TenantDto } from '@citrineos/base';
import { DEFAULT_TENANT_ID, OCPP2_0_1, OCPP2_0_1_Namespace } from '@citrineos/base';
import { BeforeCreate, BeforeUpdate, Column, DataType, Model, Table } from 'sequelize-typescript';
import { VariableAttribute } from './VariableAttribute.js';
import { VariableCharacteristics } from './VariableCharacteristics.js';
import { Component } from './Component.js';

@Table({
  indexes: [
    {
      unique: true,
      fields: ['name'],
      where: {
        instance: null,
      },
    },
  ],
})
export class Variable extends Model implements OCPP2_0_1.VariableType, VariableDto {
  static readonly MODEL_NAME: string = OCPP2_0_1_Namespace.VariableType;

  /**
   * Fields
   */

  @Column({
    type: DataType.STRING,
    unique: 'name_instance',
  })
  declare name: string;

  @Column({
    type: DataType.STRING,
    unique: 'name_instance',
  })
  declare instance?: string | null;

  /**
   * Relations
   */

  declare components?: Component[];

  declare variableAttributes?: VariableAttribute[];

  declare variableCharacteristics?: VariableCharacteristics;

  declare customData?: OCPP2_0_1.CustomDataType | null;

  // Declare the association methods, to be automatically generated by Sequelize at runtime
  public addComponent!: (variable: Component) => Promise<void>;
  public getComponents!: () => Promise<Component[]>;

  @Column({
    type: DataType.INTEGER,
    allowNull: false,
    onUpdate: 'CASCADE',
    onDelete: 'RESTRICT',
  })
  declare tenantId: number;

  declare tenant?: TenantDto;

  @BeforeUpdate
  @BeforeCreate
  static setDefaultTenant(instance: Variable) {
    if (instance.tenantId == null) {
      instance.tenantId = DEFAULT_TENANT_ID;
    }
  }

  constructor(...args: any[]) {
    super(...args);
    if (this.tenantId == null) {
      this.tenantId = DEFAULT_TENANT_ID;
    }
  }
}
